version: '3.1'
services:
  db:
    image: mysql:8.0.23
    command: --ddefault-aitentication-pligin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cuidapet_db2
      MYSQL_ROOT_PASSWORD: cuidapet

    volumes:
      - ./mysql_data/var/lib/mysql






